__version__ = "0.1.0-alpha.1"
__author__ = "Zee"
__email__ = "zee@sparselabs.org"
__license__ = "GPLv3"
__description__ = "A simple tool to switch between projects"
__url__ = "https://github.com/zhooda/goto"
